### PR TITLE
Fix broken GetFeatureInfo URLs

### PR DESCRIPTION
**Pull request by tchaddad**
The WMS GetFeatureInfo urls assembled in Identify.php have been broken due to lack of encoding/decoding.

### CODE REVIEW

**Comment by klassenjs** [comment]
I haven't looked at this closely yet, but I just want people to be thinking
about potential double encoding/decoding.  I vaguely remember a past bug
where an url encoding problem was "fixed" in the wrong spot for awhile by a
double encode or decode before we figured out what was actually going on.

To me anyway, it isn't generally clear between the layers of
OpenLayers/Dojo/XHR and PHP where there is or should be implicit
encoding/decoding and when there isn't.

**Comment by elil** [comment]
I tried searching around for those tickets or commits but didn't find them.  I also have a vague recollection of complexity around encoding.

**Comment by tchaddad** [comment]
I definitely get the word of caution, but I think this case is maybe a fairly simple one.

When you try to push a full root URL that starts with 'http://', into an array that uses ':' in the separation syntax, it will incorrectly break the string at the colon. Later on down the page when you try to use the stored URL root in assembling the full outgoing URL, you will not get the root you expect back out of the array. Instead you just get the 'http' portion that occurs before the colon. So as far as I can tell, no full WMS GetFeatureInfo url could ever have been assembled without fixing this break.

I think use of this temporary array is all just happening within this one PHP page. I've mainly tested this against the demo and in a local test install of 2.8. It seems to solve the problem for WMS, and does not seem to negatively impact Identify urls on layers of type=mapserver. 

But it's probably something others should test - I'd be interested if it solves the problems that Geoserver user was reporting with GetFeatureInfo mentioned here:

https://lists.osgeo.org/pipermail/geomoose-users/2014-September/005439.html

This fix addresses exactly the symptom described by that user. Unfortunately he fixed his own issue locally, but never filed a GitHub issue or said what he fixed.

**Comment by tchaddad** [comment]
The 3 prior (closed) issues I found that mention encoding are:

https://github.com/geomoose/geomoose/issues/29 (geocoding)
https://github.com/geomoose/geomoose/issues/37 (internationalization)
https://github.com/geomoose/geomoose/issues/51 (GetLegend URLs)

It seems like the #37 was the one with lots of issues.

**Comment by theduckylittle** [comment]
This looks safe to bring in but we should develop a test to prove it...

**Comment by theduckylittle** [comment]
Merged.

**Pull request merged**
